# Generated by Django 5.2.17 on 2026-09-08 10:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True, verbose_name='پذیرش درخواست باز است')),
                ('day_end', models.PositiveSmallIntegerField(default=19, verbose_name='دیرترین ساعت پایان کار')),
                ('max_hours', models.PositiveSmallIntegerField(default=4, verbose_name='بیشترین مدت هر رزرو (ساعت)')),
                ('min_notice', models.PositiveSmallIntegerField(default=1, verbose_name='حداقل فاصله تا امروز (روز)')),
                ('horizon_days', models.PositiveSmallIntegerField(default=90, verbose_name='تا چند روز جلوتر قابل رزرو')),
                ('request_ttl', models.PositiveSmallIntegerField(default=24, verbose_name='اعتبار هر درخواست (ساعت)')),
                ('closed_note', models.CharField(blank=True, max_length=160, verbose_name='پیام وقتی پذیرش بسته است')),
            ],
            options={
                'verbose_name': 'تنظیمات رزرو',
                'verbose_name_plural': 'تنظیمات رزرو',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نام')),
                ('note', models.CharField(blank=True, max_length=80, verbose_name='توضیح')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClosureRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='از تاریخ')),
                ('end', models.DateField(verbose_name='تا تاریخ')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='علت')),
            ],
            options={
                'verbose_name': 'قفل بازه\u200cای',
                'verbose_name_plural': 'قفل\u200cهای بازه\u200cای',
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='DateException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='تاریخ')),
                ('is_open', models.BooleanField(default=False, verbose_name='این روز آزاد باشد')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='یادداشت')),
            ],
            options={
                'verbose_name': 'استثنای روز',
                'verbose_name_plural': 'استثناهای روز',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=40, verbose_name='نام لاتین')),
                ('name_fa', models.CharField(max_length=40, verbose_name='نام فارسی')),
                ('note', models.CharField(blank=True, max_length=60, verbose_name='توضیح کوتاه')),
                ('image', models.ImageField(blank=True, upload_to='fields/', verbose_name='تصویر')),
                ('fit', models.CharField(choices=[('cover', 'پر کردن قاب'), ('contain', 'جا شدن کامل (PNG بدون پس\u200cزمینه)')], default='cover', max_length=10, verbose_name='نحوه\u200cی نمایش تصویر')),
                ('on_arc', models.BooleanField(default=True, verbose_name='روی اسلایدر کمانی نمایش داده شود')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'حوزه\u200cی کاری',
                'verbose_name_plural': 'حوزه\u200cهای کاری',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(default='یکتا', max_length=60, verbose_name='نام فارسی')),
                ('name_en', models.CharField(default='YEKTA', max_length=60, verbose_name='نام لاتین')),
                ('tagline', models.CharField(blank=True, default='مدل پوشاک، زیورآلات و کمپین — تهران', max_length=160, verbose_name='زیرنویس هیرو')),
                ('statement', models.TextField(blank=True, verbose_name='جمله\u200cی معرفی')),
                ('about', models.TextField(blank=True, verbose_name='توضیح کوتاه')),
                ('height', models.CharField(blank=True, max_length=20, verbose_name='قد')),
                ('weight', models.CharField(blank=True, max_length=20, verbose_name='وزن')),
                ('hair', models.CharField(blank=True, max_length=30, verbose_name='رنگ مو')),
                ('eyes', models.CharField(blank=True, max_length=30, verbose_name='رنگ چشم')),
                ('shoe', models.CharField(blank=True, max_length=20, verbose_name='سایز کفش')),
                ('dress', models.CharField(blank=True, max_length=20, verbose_name='سایز لباس')),
                ('city', models.CharField(blank=True, default='تهران', max_length=40, verbose_name='شهر')),
                ('instagram', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل تماس')),
                ('hero_video', models.FileField(blank=True, upload_to='hero/', verbose_name='ویدیوی هیرو')),
                ('hero_poster', models.ImageField(blank=True, upload_to='hero/', verbose_name='پوستر ویدیو')),
                ('banner_cut', models.ImageField(blank=True, upload_to='banner/', verbose_name='تصویر بنر (PNG بدون پس\u200cزمینه)')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'پروفایل یکتا',
                'verbose_name_plural': 'پروفایل یکتا',
            },
        ),
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot', models.CharField(choices=[('mini', 'سه عکس کوچک کنار جمله'), ('feature', 'عکس تمام\u200cعرض'), ('duo', 'دو عکس چسبیده'), ('plate', 'قاب پاسپارتو'), ('cover', 'شبکه\u200cی ادیتوریال'), ('reel', 'لاین افقی')], max_length=12, verbose_name='جایگاه')),
                ('image', models.ImageField(upload_to='showcase/', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='عنوان')),
                ('meta', models.CharField(blank=True, max_length=120, verbose_name='زیرنویس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'تصویر چیدمان',
                'verbose_name_plural': 'تصویرهای چیدمان',
                'ordering': ['spot', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.PositiveSmallIntegerField(unique=True, verbose_name='ساعت (۰ تا ۲۳)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ساعت شروع',
                'verbose_name_plural': 'ساعت\u200cهای شروع',
                'ordering': ['hour'],
            },
        ),
        migrations.CreateModel(
            name='WeekdayRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')], unique=True, verbose_name='روز هفته')),
                ('is_open', models.BooleanField(default=False, verbose_name='معمولاً آزاد')),
            ],
            options={
                'verbose_name': 'الگوی روز هفته',
                'verbose_name_plural': 'الگوی هفتگی',
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('full_name', models.CharField(blank=True, max_length=80, verbose_name='نام و نام خانوادگی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='دسترسی به پنل')),
                ('email_verified', models.BooleanField(default=False, verbose_name='ایمیل تایید شده')),
                ('failed_logins', models.PositiveSmallIntegerField(default=0, verbose_name='تلاش\u200cهای ناموفق')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='قفل تا')),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخرین IP')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عضویت')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'حساب\u200cها',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60, verbose_name='عمل')),
                ('target', models.CharField(blank=True, max_length=120, verbose_name='روی چه چیزی')),
                ('detail', models.TextField(blank=True, verbose_name='جزئیات')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش فعالیت',
                'verbose_name_plural': 'گزارش فعالیت',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='توکن')),
                ('kind', models.CharField(choices=[('verify', 'تایید ایمیل'), ('reset', 'بازیابی رمز')], default='verify', max_length=10, verbose_name='نوع')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('expires', models.DateTimeField(verbose_name='انقضا')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان استفاده')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL, verbose_name='حساب')),
            ],
            options={
                'verbose_name': 'توکن ایمیل',
                'verbose_name_plural': 'توکن\u200cهای ایمیل',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=120, verbose_name='نام برند / فروشگاه')),
                ('contact_name', models.CharField(max_length=80, verbose_name='نام رابط')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('city', models.CharField(blank=True, max_length=40, verbose_name='شهر')),
                ('address', models.TextField(blank=True, verbose_name='نشانی')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('instagram', models.CharField(blank=True, max_length=80, verbose_name='اینستاگرام')),
                ('reg_no', models.CharField(blank=True, max_length=40, verbose_name='شناسه صنفی / ثبت')),
                ('is_trusted', models.BooleanField(default=False, verbose_name='کارفرمای مورد اعتماد')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='مسدود')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت داخلی یکتا')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL, verbose_name='حساب')),
            ],
            options={
                'verbose_name': 'کارفرما',
                'verbose_name_plural': 'کارفرماها',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CollabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('start_hour', models.PositiveSmallIntegerField(verbose_name='ساعت شروع')),
                ('hours', models.PositiveSmallIntegerField(default=1, verbose_name='مدت (ساعت)')),
                ('brief', models.TextField(blank=True, verbose_name='شرح کار')),
                ('place', models.CharField(blank=True, max_length=140, verbose_name='محل کار')),
                ('budget', models.CharField(blank=True, max_length=60, verbose_name='بودجه\u200cی پیشنهادی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پاسخ'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('alternative', 'پیشنهاد زمان جایگزین'), ('cancelled', 'لغو شده'), ('expired', 'منقضی شده'), ('done', 'انجام شده')], default='pending', max_length=12, verbose_name='وضعیت')),
                ('reply', models.TextField(blank=True, verbose_name='پیام یکتا')),
                ('alt_date', models.DateField(blank=True, null=True, verbose_name='تاریخ جایگزین')),
                ('alt_start', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ساعت جایگزین')),
                ('alt_hours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='مدت جایگزین')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تصمیم')),
                ('snap_company', models.CharField(blank=True, max_length=120, verbose_name='برند (ثبت\u200cشده)')),
                ('snap_contact', models.CharField(blank=True, max_length=80, verbose_name='رابط (ثبت\u200cشده)')),
                ('snap_phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن (ثبت\u200cشده)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='اعتبار تا')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='دیده شده')),
                ('from_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP ثبت')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='main.employer', verbose_name='کارفرما')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='main.field', verbose_name='حوزه')),
            ],
            options={
                'verbose_name': 'درخواست همکاری',
                'verbose_name_plural': 'درخواست\u200cهای همکاری',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('model', 'یکتا'), ('employer', 'کارفرما'), ('system', 'سیستم')], max_length=10, verbose_name='فرستنده')),
                ('body', models.TextField(verbose_name='متن پیام')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خواندن')),
                ('hidden', models.BooleanField(default=False, verbose_name='مخفی شده')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.collabrequest', verbose_name='درخواست')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان')),
                ('meta', models.CharField(blank=True, max_length=120, verbose_name='زیرعنوان')),
                ('cover', models.ImageField(blank=True, upload_to='works/', verbose_name='کاور')),
                ('year', models.CharField(blank=True, max_length=10, verbose_name='سال')),
                ('photographer', models.CharField(blank=True, max_length=80, verbose_name='عکاس')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='main.field', verbose_name='حوزه')),
            ],
            options={
                'verbose_name': 'کار',
                'verbose_name_plural': 'کارها',
                'ordering': ['order', '-created'],
            },
        ),
        migrations.CreateModel(
            name='WorkShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='works/shots/', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='توضیح')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='main.work', verbose_name='کار')),
            ],
            options={
                'verbose_name': 'قاب',
                'verbose_name_plural': 'قاب\u200cها',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='collabrequest',
            index=models.Index(fields=['date', 'status'], name='main_collab_date_368a3f_idx'),
        ),
        migrations.AddIndex(
            model_name='collabrequest',
            index=models.Index(fields=['status', '-created'], name='main_collab_status_be95c6_idx'),
        ),
    ]
