# Generated by Django 5.2.14 on 2026-09-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='activity',
            field=models.CharField(choices=[('apparel', 'پوشاک'), ('jewellery', 'زیورآلات و اکسسوری'), ('beauty', 'آرایشی و بهداشتی'), ('bridal', 'عروس و مزون'), ('sports', 'ورزشی'), ('agency', 'آژانس تبلیغاتی'), ('studio', 'عکاسی و استودیو'), ('other', 'سایر')], default='other', max_length=20, verbose_name='حیطه\u200cی فعالیت'),
        ),
        migrations.AddField(
            model_name='employer',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='employer',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی'),
        ),
    ]
