# Generated by Django 5.2.17 on 2026-09-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employer_activity_employer_lat_employer_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='links',
            field=models.TextField(blank=True, help_text='هر لینک در یک خط.', verbose_name='لینک\u200cهای دیگر'),
        ),
    ]
