# Generated by Django 5.2.17 on 2026-09-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_employer_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, help_text='اختیاری — اگر خالی بماند، حرف اول نام به\u200cجایش نشان داده می\u200cشود.', upload_to='brands/', verbose_name='لوگو یا تصویر'),
        ),
    ]
