# Generated by Django 5.2.17 on 2026-09-10 12:29

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify

def fill_field_slugs(apps, schema_editor):
    """
    برای هر مجموعه یک نشانی یکتا می‌سازد.

    اگر دو مجموعه به یک اسلاگ برسند (مثلاً هر دو فارسی خالص باشند و
    slugify چیزی برنگرداند)، شماره‌ی ردیف به تهش می‌چسبد تا یکتا بماند.
    """
    Field = apps.get_model("main", "Field")
    seen = set()

    for row in Field.objects.all().order_by("id"):
        base = slugify(row.en or row.name_fa, allow_unicode=True) or "field"
        slug = base
        i = 2
        while slug in seen:
            slug = "%s-%s" % (base, i)
            i += 1
        seen.add(slug)
        row.slug = slug
        row.save(update_fields=["slug"])


def move_works(apps, schema_editor):
    """
    کارها و قاب‌هایشان به مدل تازه‌ی Photo منتقل می‌شوند.

    ImageField فقط مسیر فایل را نگه می‌دارد، پس با کپی‌کردن همان رشته،
    خودِ عکس‌های آپلودشده سر جایشان می‌مانند و چیزی از دست نمی‌رود.
    """
    Work = apps.get_model("main", "Work")
    WorkShot = apps.get_model("main", "WorkShot")
    Photo = apps.get_model("main", "Photo")

    order = 0

    for work in Work.objects.all().order_by("order", "id"):
        if work.cover:
            Photo.objects.create(
                image=work.cover,
                title=work.title,
                story=work.meta or "",
                field_id=work.field_id,
                year=work.year or "",
                photographer=work.photographer or "",
                is_published=work.is_published,
                order=order,
            )
            order += 1

        for shot in WorkShot.objects.filter(work_id=work.id).order_by("order", "id"):
            Photo.objects.create(
                image=shot.image,
                title=shot.caption or work.title,
                story=work.meta or "",
                field_id=work.field_id,
                year=work.year or "",
                photographer=work.photographer or "",
                is_published=work.is_published,
                order=order,
            )
            order += 1



class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_brand_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollabKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="نام")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=70,
                        unique=True,
                        verbose_name="نشانی",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=90, verbose_name="توضیح کوتاه"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
            ],
            options={
                "verbose_name": "نوع همکاری",
                "verbose_name_plural": "نوع\u200cهای همکاری",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(unique=True, verbose_name="روز")),
                (
                    "visits",
                    models.PositiveIntegerField(default=0, verbose_name="بازدید"),
                ),
                (
                    "guests",
                    models.PositiveIntegerField(default=0, verbose_name="بازدیدکننده"),
                ),
                (
                    "clicks",
                    models.PositiveIntegerField(
                        default=0, verbose_name="کلیک روی عکس\u200cها"
                    ),
                ),
                (
                    "requests",
                    models.PositiveIntegerField(default=0, verbose_name="درخواست تازه"),
                ),
                (
                    "signups",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ثبت\u200cنام تازه"
                    ),
                ),
                (
                    "tickets",
                    models.PositiveIntegerField(
                        default=0, verbose_name="پیام پشتیبانی"
                    ),
                ),
                (
                    "top",
                    models.TextField(
                        blank=True,
                        help_text="هر خط: شناسه | عنوان | تعداد کلیک",
                        verbose_name="پرکلیک\u200cترین عکس\u200cها",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="ساخته شده"),
                ),
            ],
            options={
                "verbose_name": "گزارش شبانه",
                "verbose_name_plural": "گزارش\u200cهای شبانه",
                "ordering": ["-day"],
            },
        ),
        migrations.CreateModel(
            name="ModelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="نام")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=70,
                        unique=True,
                        verbose_name="نشانی",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=90, verbose_name="توضیح کوتاه"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
            ],
            options={
                "verbose_name": "نوع مدلینگ",
                "verbose_name_plural": "نوع\u200cهای مدلینگ",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="نام")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=70,
                        unique=True,
                        verbose_name="نشانی",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=90, verbose_name="توضیح کوتاه"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
            ],
            options={
                "verbose_name": "محل",
                "verbose_name_plural": "محل\u200cها",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=60, verbose_name="نام"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="شماره تماس")),
                ("body", models.TextField(verbose_name="متن پیام")),
                (
                    "is_done",
                    models.BooleanField(default=False, verbose_name="رسیدگی شد"),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان"),
                ),
            ],
            options={
                "verbose_name": "پیام پشتیبانی",
                "verbose_name_plural": "پیام\u200cهای پشتیبانی",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="VisitDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(unique=True, verbose_name="روز")),
                (
                    "hits",
                    models.PositiveIntegerField(default=0, verbose_name="بازدید صفحه"),
                ),
                (
                    "guests",
                    models.PositiveIntegerField(
                        default=0, verbose_name="بازدیدکننده\u200cی تازه"
                    ),
                ),
            ],
            options={
                "verbose_name": "بازدید روزانه",
                "verbose_name_plural": "بازدید روزانه",
                "ordering": ["-day"],
            },
        ),
        migrations.AlterModelOptions(
            name="field",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "حوزه / مجموعه",
                "verbose_name_plural": "حوزه\u200cها و مجموعه\u200cها",
            },
        ),
        migrations.AddField(
            model_name="account",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                unique=True,
                verbose_name="شماره تلفن",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="phone_verified",
            field=models.BooleanField(default=False, verbose_name="شماره تایید شده"),
        ),
        migrations.AddField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "مدیر سایت"),
                    ("model", "یکتا (مدل)"),
                    ("employer", "کارفرما"),
                ],
                default="employer",
                max_length=10,
                verbose_name="نقش",
            ),
        ),
        migrations.AddField(
            model_name="bookingsettings",
            name="floor_price",
            field=models.PositiveIntegerField(
                default=0,
                help_text="کارفرما نمی\u200cتواند عددی کمتر از این پیشنهاد بدهد. صفر یعنی بدون کف.",
                verbose_name="کف بودجه\u200cی هر آفیش (تومان)",
            ),
        ),
        migrations.AddField(
            model_name="bookingsettings",
            name="price_note",
            field=models.CharField(
                blank=True,
                default="هزینه\u200cی هر آفیش بسته به نوع همکاری، مدت و محل متغیر است.",
                max_length=200,
                verbose_name="توضیح زیر بودجه",
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="link",
            field=models.URLField(blank=True, verbose_name="لینک"),
        ),
        migrations.AddField(
            model_name="collabrequest",
            name="budget_amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="بودجه\u200cی پیشنهادی (تومان)"
            ),
        ),
        migrations.AddField(
            model_name="collabrequest",
            name="budget_mode",
            field=models.CharField(
                choices=[
                    ("set", "عدد پیشنهادی دارم"),
                    ("ask", "در درخواست ذکر می\u200cکنم"),
                ],
                default="set",
                max_length=5,
                verbose_name="نحوه\u200cی بودجه",
            ),
        ),
        migrations.AddField(
            model_name="collabrequest",
            name="crew",
            field=models.CharField(
                blank=True, max_length=140, verbose_name="تیم و همراهان"
            ),
        ),
        migrations.AddField(
            model_name="employer",
            name="added_by_model",
            field=models.BooleanField(
                default=False, verbose_name="دستی توسط یکتا اضافه شده"
            ),
        ),
        migrations.AddField(
            model_name="employer",
            name="signup_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP ثبت\u200cنام"
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="blurb",
            field=models.TextField(blank=True, verbose_name="معرفی صفحه\u200cی مجموعه"),
        ),
        migrations.AddField(
            model_name="field",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                default="",
                max_length=60,
                verbose_name="نشانی صفحه",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="banner_bg",
            field=models.CharField(
                default="#1E6B57",
                help_text="رنگ اصلی پشت تصویر بنر — از انتخابگر رنگ همین\u200cجا عوضش کن.",
                max_length=9,
                verbose_name="رنگ پس\u200cزمینه\u200cی بنر",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="banner_bg2",
            field=models.CharField(
                default="#0E2B24",
                help_text="پس\u200cزمینه یک محو ملایم بین این دو رنگ است.",
                max_length=9,
                verbose_name="رنگ دوم بنر (گوشه\u200cها)",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="banner_ink",
            field=models.CharField(
                default="#FFFFFF", max_length=9, verbose_name="رنگ متن روی بنر"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="شماره تماس عمومی"
            ),
        ),
        migrations.AddField(
            model_name="showcase",
            name="field",
            field=models.ForeignKey(
                blank=True,
                help_text="با کلیک روی این تصویر، کاربر به صفحه\u200cی این مجموعه می\u200cرود. خالی نگذار — هیچ تصویری نباید بی\u200cمقصد باشد.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="showcases",
                to="main.field",
                verbose_name="مجموعه\u200cی مقصد",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="دسترسی به پنل جنگو"),
        ),
        migrations.AlterField(
            model_name="collabrequest",
            name="budget",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="بودجه (متن قدیمی)"
            ),
        ),
        migrations.AlterField(
            model_name="collabrequest",
            name="place",
            field=models.CharField(
                blank=True, max_length=140, verbose_name="نشانی دقیق محل"
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="اگر خالی بماند، تازه\u200cترین عکسِ همین مجموعه خودکار تصویر سردر می\u200cشود.",
                upload_to="fields/",
                verbose_name="تصویر ثابت (اختیاری)",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="on_arc",
            field=models.BooleanField(
                default=True, verbose_name="روی اسلایدر صفحه\u200cی اول"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="banner_cut",
            field=models.ImageField(
                blank=True,
                help_text="بهترین اندازه: ۱۶۰۰×۲۴۰۰ پیکسل، PNG با پس\u200cزمینه\u200cی شفاف، قدِ کامل، پاها روی لبه\u200cی پایین کادر.",
                upload_to="banner/",
                verbose_name="تصویر بنر (PNG بدون پس\u200cزمینه)",
            ),
        ),
        migrations.AddField(
            model_name="collabrequest",
            name="kind",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to="main.collabkind",
                verbose_name="نوع همکاری",
            ),
        ),
        migrations.AddField(
            model_name="collabrequest",
            name="model_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to="main.modeltype",
                verbose_name="نوع مدلینگ",
            ),
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="photos/", verbose_name="تصویر")),
                (
                    "title",
                    models.CharField(blank=True, max_length=90, verbose_name="عنوان"),
                ),
                (
                    "story",
                    models.TextField(
                        blank=True,
                        help_text="همان متنی که زیر عکس، در صفحه\u200cی تک\u200cعکس دیده می\u200cشود.",
                        verbose_name="توضیح پروژه",
                    ),
                ),
                (
                    "year",
                    models.CharField(blank=True, max_length=10, verbose_name="سال"),
                ),
                (
                    "photographer",
                    models.CharField(blank=True, max_length=80, verbose_name="عکاس"),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="برند / کارفرما"
                    ),
                ),
                (
                    "on_strip",
                    models.BooleanField(
                        default=False, verbose_name="در نوار متحرک صفحه\u200cی اول"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="منتشر شده"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "clicks",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="تعداد کلیک"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="افزوده شده"),
                ),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="main.field",
                        verbose_name="مجموعه",
                    ),
                ),
                (
                    "model_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="main.modeltype",
                        verbose_name="نوع مدلینگ",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="main.place",
                        verbose_name="محل",
                    ),
                ),
            ],
            options={
                "verbose_name": "عکس",
                "verbose_name_plural": "عکس\u200cها",
                "ordering": ["order", "-created", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PhotoClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="زمان"
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_rows",
                        to="main.photo",
                        verbose_name="عکس",
                    ),
                ),
            ],
            options={
                "verbose_name": "کلیک عکس",
                "verbose_name_plural": "کلیک\u200cهای عکس",
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="collabrequest",
            name="place_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to="main.place",
                verbose_name="محل",
            ),
        ),
        migrations.RunPython(move_works, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="workshot",
            name="work",
        ),
        migrations.DeleteModel(
            name="Work",
        ),
        migrations.DeleteModel(
            name="WorkShot",
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["is_published", "order"], name="main_photo_is_publ_192752_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(fields=["-clicks"], name="main_photo_clicks_9bd729_idx"),
        ),
        migrations.RunPython(fill_field_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="field",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                max_length=60,
                unique=True,
                verbose_name="نشانی صفحه",
            ),
        ),
    ]
